/**
 * @file callbacks.h
 * @author zone-1614 (you@domain.com)
 * @brief glfw回调函数指针的定义
 * @version 0.1
 * @date 2023-06-05
 * 
 * @copyright Copyright (c) 2023
 * 
 */
#pragma once

#include <GLFW/glfw3.h>

namespace zmesh {
namespace gl {

/*
GLFW divides keyboard input into two categories; key events and character events. 
Key events relate to actual physical keyboard keys, whereas character events relate to the Unicode code points generated by pressing some of them.
*/

using KeyCallback = void(*)(
    GLFWwindow*, 
    int /* key */, 
    int /* scancode */, 
    int /* action */, 
    int /* mods */
);

using CharacterCallback = void(*)(
    GLFWwindow*,
    unsigned int /* codepoint */
);

using CursorPosCallback = void(*)(
    GLFWwindow*,
    double /* xpos */,
    double /* ypos */
);

using CursorEnterCallback = void(*)(
    GLFWwindow*,
    int /* entered */
);

using MouseButtonCallback = void(*)(
    GLFWwindow*,
    int /* button */,
    int /* action */,
    int /* mods */
);

using ScrollCallback = void(*)(
    GLFWwindow*,
    double /* xoffset */,
    double /* yoffset */
);

using DropCallback = void(*)(
    GLFWwindow*,
    int /* count */,
    const char** /* paths */
);

using FramebufferSizeCallback = void(*)(
    GLFWwindow*,
    int /* width */,
    int /* height */
);

}
}